### ISSUE TITLE
AttributeError: 'MainApp' object has no attribute 'register'

### ISSUE THREAD

**Issue by LucaRicardo** [ComradOrg/Comrad#21]
I got the previous error solved but got a new one right after I entered the username, here's the entire error:
```
 Traceback (most recent call last):
   File "main.py", line 455, in <module>
     loop.run_until_complete(MainApp().app_func())
   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
     return future.result()
   File "main.py", line 418, in run_wrapper
     await self.async_run() #async_lib='asyncio')
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivy/app.py", line 962, in async_run
     await async_runTouchApp(async_lib=async_lib)
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivy/base.py", line 595, in async_runTouchApp
     await EventLoop.async_mainloop()
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivy/base.py", line 362, in async_mainloop
     await self.async_idle()
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivy/base.py", line 424, in async_idle
     self.dispatch_input()
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivy/base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivy/base.py", line 308, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivymd/uix/behaviors/ripplebehavior.py", line 245, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivymd/uix/button.py", line 969, in on_touch_up
     return super().on_touch_up(touch)
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivy/uix/behaviors/button.py", line 179, in on_touch_up
     self.dispatch('on_release')
   File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "/home/lr/git/Komrade/Komrade.venv/lib/python3.7/site-packages/kivy/lang/builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "/home/lr/git/Komrade/app/screens/login/login.kv", line 123, in <module>
     on_release: self.register()
   File "/home/lr/git/Komrade/app/screens/login/login.py", line 21, in register
     app.register(un)
 AttributeError: 'MainApp' object has no attribute 'register'
```

**Comment by quadrismegistus** [comment]
hey, sorry about this. the frontend part of the app is kind of broken while I work on the backend for a minute. if you want to poke around there, checkout the backend python files. I want to try documenting things more. also, if you want to join a signal group chat, lmk. email: ryan.heuser@gmail.com

**Comment by LucaRicardo** [comment]
Well, now I got my previous error again 
`AttributeError: 'MainApp' object has no attribute 'async_run'`
